# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs ( https://dart.dev/tools#ides-and-editors ). The analyzer can also be# invoked from the command line by running `flutter analyze`.
# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/generated
    - lib/*/*.g.dart
    - lib/*/*/*.g.dart
    - lib/*/*/*/*.g.dart
    - lib/*/*/*/*/*.g.dart
    - lib/*/*/*/*/*/*.g.dart
  errors:
    fixme: ignore

linter:
  rules:
    sort_constructors_first: true
    prefer_single_quotes: true
    always_specify_types: true
    lines_longer_than_80_chars: true
    always_put_required_named_parameters_first: false
    avoid_classes_with_only_static_members: false
    null_check_on_nullable_type_parameter: true
    cast_nullable_to_non_nullable: true
    avoid_empty_else: true
    avoid_escaping_inner_quotes: true
    avoid_double_and_int_checks: true
    always_declare_return_types: true
    annotate_overrides: true
    avoid_bool_literals_in_conditional_expressions: true
    avoid_dynamic_calls: true
    avoid_field_initializers_in_const_classes: true
    avoid_function_literals_in_foreach_calls: true
    avoid_null_checks_in_equality_operators: true
    avoid_redundant_argument_values: true
    avoid_relative_lib_imports: true
    avoid_renaming_method_parameters: true
    avoid_slow_async_io: true
    avoid_type_to_string: true
    avoid_unnecessary_containers: true
    avoid_unused_constructor_parameters: true
    avoid_void_async: true
    cancel_subscriptions: true
    exhaustive_cases: true
    leading_newlines_in_multiline_strings: true
    no_duplicate_case_values: true
    no_logic_in_create_state: true
    null_closures: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_is_not_operator: true
    sized_box_for_whitespace: true
    sort_child_properties_last: true